[providers]
python = "3.12"

[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd frontend && npm install && npm run build && cd .."
]

[start]
cmd = "python backend.py"

